package tui

const (
	ButtonBack      = "Back"
	ButtonHome      = "Home"
	ButtonClose     = "Close"
	ButtonOK        = "OK"
	ButtonStart     = "Start"
	ButtonSelect    = "Select"
	ButtonSearch    = "Search"
	ButtonRunBLAST  = "Run BLAST"
	ButtonApply     = "Apply"
	ButtonAuto      = "Auto identify"
	ButtonSave      = "Save"
	ButtonView      = "View"
	ButtonHelp      = "Help"
	ButtonFilter    = "Filter"
	ButtonCopy      = "Copy"
	ButtonExport    = "Export"
	ButtonExportAll = "Export all"
	ButtonPaste     = "Paste"
	ButtonCancel    = "Cancel"
	ButtonRetry     = "Retry"
	ButtonSkip      = "Skip"
	ButtonInstall   = "Install"
	ButtonYes       = "Yes"
	ButtonNo        = "No"
	ButtonSelectAll = "Select all"
	ButtonClear     = "Clear"
	ButtonClearFilter = "Clear filter"
	ButtonToggle    = "Toggle"
)

const (
	ShortcutBack      = "Esc"
	ShortcutHome      = "Ctrl+O"
	ShortcutConfirm   = "Enter"
	ShortcutApply     = "Enter"
	ShortcutPaste     = "Ctrl+V"
	ShortcutCancel    = "Esc"
	ShortcutAuto      = "Enter"
	ShortcutSelectAll = "Ctrl+A"
	ShortcutClear     = "Ctrl+N"
	ShortcutClearFilter = "Ctrl+L"
	ShortcutToggle    = "Space"
	ShortcutCopy      = "Ctrl+Shift+C"
	ShortcutFilter    = "Ctrl+F"
	ShortcutExport    = "Ctrl+G"
	ShortcutExportAll = "Ctrl+D"
	ShortcutRetry     = "Ctrl+R"
	ShortcutHelp      = "F1"
)
