package report

import (
	"crypto/md5"
	"crypto/sha1"
	"crypto/sha256"
	"encoding/hex"
	"fmt"
	"os"
	"os/user"
	"path/filepath"
	"runtime"
	"strings"
	"time"

	"github.com/KiriKirby/phytozome-go/internal/model"
	"github.com/KiriKirby/phytozome-go/internal/prompt"
)

func SampleKeywordReportData() ReportData {
	now := time.Now()
	queryStart := now.Add(-12*time.Minute - 34*time.Second)
	searchEnd := queryStart.Add(2*time.Minute + 9*time.Second)
	reviewStart := searchEnd.Add(5 * time.Second)
	exportStart := now.Add(-2*time.Minute - 25*time.Second)
	exportEnd := now.Add(-18 * time.Second)
	session := sampleSession()
	files := sampleFiles(now, session.OutputDir)
	return ReportData{
		Title:       "Keyword Data Analysis Report",
		Mode:        "keyword",
		GeneratedAt: now,
		Software: SoftwareInfo{
			Name:       "phytozome GO",
			Author:     "wangsychn",
			Repository: "https://github.com/KiriKirby/phytozome-go",
			Version:    "dev",
			GoVersion:  runtime.Version(),
		},
		UserSession: session,
		System: SystemInfo{
			OS:           runtime.GOOS,
			OSVersion:    "not available in this sample run",
			Architecture: runtime.GOARCH,
			CPUCount:     runtime.NumCPU(),
			Memory:       "not available in this sample run",
		},
		TimeWindow: TimeWindow{
			QueryStart:     queryStart,
			SearchEnd:      searchEnd,
			ReviewStart:    reviewStart,
			ExportStart:    exportStart,
			ExportEnd:      exportEnd,
			ReportRendered: now,
		},
		Files: files,
		Keyword: KeywordReportData{
			Database: "lemna",
			Species: SpeciesReport{
				DisplayLabel: "Spirodela polyrhiza 7498 v3",
				GenomeLabel:  "Sp7498v3",
				CommonName:   "greater duckweed",
				SearchAlias:  "Spirodela polyrhiza",
				JBrowseName:  "Sp7498v3",
				ProteomeID:   "not available in this run",
				ReleaseDate:  "2024-11-18",
				IsOfficial:   "true",
				SourceNotes:  "sample release-backed keyword search context; all values are demonstration report data",
			},
			SearchTerms: []KeywordTermReport{
				{SearchTerm: "phenylalanine ammonia lyase", InputType: "plain keyword", SearchType: "keyword", QueryOrder: 1, TotalRows: 11, SelectedRows: 5, LabelName: "PAL", MatchingNotes: "matched against already-loaded GFF3/AHRD annotation text", DurationMillis: 38400},
				{SearchTerm: "cinnamate 4-hydroxylase", InputType: "plain keyword", SearchType: "keyword", QueryOrder: 2, TotalRows: 6, SelectedRows: 3, LabelName: "C4H", MatchingNotes: "matched against annotation fields in the current result set", DurationMillis: 29500},
				{SearchTerm: "4CL", InputType: "identifier-like term", SearchType: "keyword", QueryOrder: 3, TotalRows: 4, SelectedRows: 2, LabelName: "4CL", MatchingNotes: "matched through alias and description fields already present in parsed rows", DurationMillis: 21700},
				{SearchTerm: "CCR2", InputType: "identifier-like term", SearchType: "keyword", QueryOrder: 4, TotalRows: 2, SelectedRows: 1, LabelName: "CCR2", MatchingNotes: "matched through existing row aliases", DurationMillis: 16400},
				{SearchTerm: "CAD8", InputType: "identifier-like term", SearchType: "keyword", QueryOrder: 5, TotalRows: 0, SelectedRows: 0, LabelName: "CAD8", MatchingNotes: "no rows in the current result table", DurationMillis: 11800},
			},
			LabelTraces: []KeywordLabelReport{
				{SearchTerm: "phenylalanine ammonia lyase", FinalLabel: "PAL", SourceField: "user input", SourceValue: "PAL", Method: "manual label", Explanation: "The user-supplied label was preserved for row readability and sequence headers."},
				{SearchTerm: "cinnamate 4-hydroxylase", FinalLabel: "C4H", SourceField: "user input", SourceValue: "C4H", Method: "manual label", Explanation: "The label was entered before keyword search and applied to rows from the term."},
				{SearchTerm: "4CL", FinalLabel: "4CL", SourceField: "search term", SourceValue: "4CL", Method: "auto-identify", Explanation: "The short identifier-like term was retained as the final label in the sample data."},
				{SearchTerm: "CCR2", FinalLabel: "CCR2", SourceField: "alias", SourceValue: "CCR2; CCR-like", Method: "auto-identify", Explanation: "The best alias candidate in already-loaded row data supplied the label."},
				{SearchTerm: "CAD8", FinalLabel: "CAD8", SourceField: "search term", SourceValue: "CAD8", Method: "no-hit fallback in report data", Explanation: "No rows were found; the input term remains the traceable label. No extra lookup was run."},
			},
			Selection: KeywordSelectionStats{
				TotalRows:      23,
				SelectedRows:   11,
				UnselectedRows: 12,
				SearchTerms:    5,
				TermsWithHits:  4,
				TermsZeroHits:  1,
				GeneratedFiles: len(files),
			},
			Provenance: []ProvenanceSlice{
				{Label: "local release parsed", Count: 138, Explanation: "Values parsed from already-loaded GFF3/AHRD release assets."},
				{Label: "generated/internal", Count: 46, Explanation: "Row numbers, search-term tags, labels, and export metadata generated by the program."},
				{Label: "cache-backed", Count: 22, Explanation: "Values reused from cache state already used in the normal workflow."},
				{Label: "unavailable/missing", Count: 18, Explanation: "Expected fields absent from current rows or not collected in this sample run."},
			},
			ColumnCompleteness: []ColumnCompleteness{
				{Column: "row", FilledRows: 11, EmptyRows: 0, TotalRows: 11, FilledRatio: "100.0%", Source: "phytozome GO"},
				{Column: "search_term", FilledRows: 11, EmptyRows: 0, TotalRows: 11, FilledRatio: "100.0%", Source: "user input"},
				{Column: "label_name", FilledRows: 11, EmptyRows: 0, TotalRows: 11, FilledRatio: "100.0%", Source: "user or label logic"},
				{Column: "transcript", FilledRows: 9, EmptyRows: 2, TotalRows: 11, FilledRatio: "81.8%", Source: "selected database"},
				{Column: "description", FilledRows: 11, EmptyRows: 0, TotalRows: 11, FilledRatio: "100.0%", Source: "source annotation"},
				{Column: "uniprot", FilledRows: 6, EmptyRows: 5, TotalRows: 11, FilledRatio: "54.5%", Source: "source annotation"},
			},
			QualityChecks: []QualityCheck{
				{Name: "Search terms with zero hits", Result: "warning", Count: "1 of 5", Rule: "warn when count > 0", Explanation: "One term produced no current rows and is preserved in the traceability table.", Source: "search groups"},
				{Name: "Rows missing label", Result: "pass", Count: "0 of 23", Rule: "warn when any selected row lacks label", Explanation: "All selected rows have a label in this sample.", Source: "row data"},
				{Name: "Rows missing transcript ID", Result: "warning", Count: "2 of 23", Rule: "warn when missing in selected rows", Explanation: "Two rows did not expose transcript identifiers in current data.", Source: "row data"},
				{Name: "Rows missing description", Result: "pass", Count: "0 of 23", Rule: "warn when description blank", Explanation: "All rows have an annotation description.", Source: "row data"},
				{Name: "Sequence export completeness", Result: "warning", Count: "10 written / 11 requested", Rule: "warn when written < requested", Explanation: "One selected row did not have an available peptide sequence in the sample state.", Source: "sequence export state"},
				{Name: "Raw Excel completeness", Result: "pass", Count: "23 rows", Rule: "pass when raw export requested and all rows written", Explanation: "Raw Excel contains all current rows in this sample.", Source: "export settings"},
			},
			Columns: sampleKeywordColumns("lemna", true, nil),
			ExportSettings: []NameValue{
				{Name: "File base name", Value: "spirodela_lignin_keyword", Explanation: "Base name used for selected Excel, raw Excel, peptide text, and raw peptide text outputs."},
				{Name: "Output folder", Value: session.OutputDir, Explanation: "Destination folder for the current export action."},
				{Name: "Write selected Excel", Value: "true", Explanation: "Selected rows are written to the main workbook."},
				{Name: "Write raw Excel and raw text", Value: "true", Explanation: "All current rows are written to _raw.xlsx, and _raw.txt is also written when text export is enabled."},
				{Name: "Write peptide text", Value: "true", Explanation: "Peptide sequences are written for selected rows with sequence IDs."},
				{Name: "Write report PDF", Value: "true", Explanation: "This PDF is generated once for the export action."},
			},
			GenerationSteps: sampleSteps(exportStart, now),
			Sequences: SequenceAudit{
				Requested:       true,
				RequestedCount:  11,
				WrittenCount:    10,
				SkippedCount:    1,
				TotalCharacters: 5473,
				Records: []SequenceRecord{
					{Row: 1, SearchTerm: "phenylalanine ammonia lyase", Label: "PAL", SequenceID: "Sp7498v3_PAL_001", Transcript: "Sp7498v3_T000381", Status: "written", Length: 531, Source: "already-resolved protein FASTA state"},
					{Row: 2, SearchTerm: "phenylalanine ammonia lyase", Label: "PAL", SequenceID: "Sp7498v3_PAL_002", Transcript: "Sp7498v3_T000382", Status: "written", Length: 529, Source: "already-resolved protein FASTA state"},
					{Row: 8, SearchTerm: "cinnamate 4-hydroxylase", Label: "C4H", SequenceID: "Sp7498v3_C4H_001", Transcript: "Sp7498v3_T008193", Status: "written", Length: 507, Source: "already-resolved protein FASTA state"},
					{Row: 17, SearchTerm: "CCR2", Label: "CCR2", SequenceID: "Sp7498v3_CCR_002", Transcript: "not available in this run", Status: "skipped", Length: 0, Source: "sequence ID absent from current row"},
				},
				QuerySummaries: []SequenceQuerySummary{
					{QueryLabel: "PAL", QueryKind: "selected keyword peptide rows", RequestedCount: 4, WrittenCount: 4, SkippedCount: 0, AverageLength: 530, MinLength: 529, MaxLength: 532, TotalLength: 2120, SourceSummary: "already-resolved protein FASTA state"},
					{QueryLabel: "C4H", QueryKind: "selected keyword peptide rows", RequestedCount: 2, WrittenCount: 1, SkippedCount: 1, AverageLength: 507, MinLength: 507, MaxLength: 507, TotalLength: 507, SourceSummary: "already-resolved protein FASTA state"},
					{QueryLabel: "4CL", QueryKind: "selected keyword peptide rows", RequestedCount: 2, WrittenCount: 2, SkippedCount: 0, AverageLength: 489, MinLength: 488, MaxLength: 490, TotalLength: 978, SourceSummary: "already-resolved protein FASTA state"},
					{QueryLabel: "CCR2", QueryKind: "selected keyword peptide rows", RequestedCount: 2, WrittenCount: 2, SkippedCount: 0, AverageLength: 476, MinLength: 475, MaxLength: 477, TotalLength: 952, SourceSummary: "already-resolved protein FASTA state"},
					{QueryLabel: "CAD8", QueryKind: "selected keyword peptide rows", RequestedCount: 1, WrittenCount: 1, SkippedCount: 0, AverageLength: 916, MinLength: 916, MaxLength: 916, TotalLength: 916, SourceSummary: "already-resolved protein FASTA state"},
				},
			},
		},
	}
}

func SampleKeywordPhytozomeReportData() ReportData {
	data := SampleKeywordReportData()
	data.Keyword.Database = "phytozome"
	data.Keyword.Species = SpeciesReport{
		DisplayLabel: "Arabidopsis thaliana TAIR10",
		GenomeLabel:  "Athaliana",
		CommonName:   "thale cress",
		SearchAlias:  "Arabidopsis thaliana",
		JBrowseName:  "Athaliana",
		ProteomeID:   "447",
		ReleaseDate:  "2025-03-14",
		IsOfficial:   "not applicable to this source",
		SourceNotes:  "sample phytozome keyword context; rows represent direct source-client results rather than release-parsed lemna rows",
	}
	data.Keyword.Columns = sampleKeywordColumns("phytozome", true, nil)
	data.Keyword.ColumnCompleteness = []ColumnCompleteness{
		{Column: "row", FilledRows: 11, EmptyRows: 0, TotalRows: 11, FilledRatio: "100.0%", Source: "phytozome GO"},
		{Column: "search_term", FilledRows: 11, EmptyRows: 0, TotalRows: 11, FilledRatio: "100.0%", Source: "user input"},
		{Column: "label_name", FilledRows: 11, EmptyRows: 0, TotalRows: 11, FilledRatio: "100.0%", Source: "user or label logic"},
		{Column: "protein_id", FilledRows: 11, EmptyRows: 0, TotalRows: 11, FilledRatio: "100.0%", Source: "selected database"},
		{Column: "transcript", FilledRows: 11, EmptyRows: 0, TotalRows: 11, FilledRatio: "100.0%", Source: "selected database"},
		{Column: "description", FilledRows: 11, EmptyRows: 0, TotalRows: 11, FilledRatio: "100.0%", Source: "source annotation"},
	}
	data.Keyword.Provenance = []ProvenanceSlice{
		{Label: "direct source result", Count: 132, Explanation: "Values preserved from current phytozome keyword result rows."},
		{Label: "generated/internal", Count: 44, Explanation: "Row tags, labels, export metadata, and report audit values generated by the program."},
		{Label: "unavailable/missing", Count: 17, Explanation: "Fields absent from current rows or not collected in this sample state."},
	}
	return data
}

func SampleBlastReportData() ReportData {
	now := time.Now()
	queryStart := now.Add(-26*time.Minute - 10*time.Second)
	searchEnd := queryStart.Add(17*time.Minute + 45*time.Second)
	reviewStart := searchEnd.Add(35 * time.Second)
	exportStart := now.Add(-4*time.Minute - 40*time.Second)
	exportEnd := now.Add(-28 * time.Second)
	session := sampleSession()
	files := sampleBlastFiles(now, session.OutputDir)
	return ReportData{
		Title:       "BLAST Data Analysis Report",
		Mode:        "blast",
		GeneratedAt: now,
		Software: SoftwareInfo{
			Name:       "phytozome GO",
			Author:     "wangsychn",
			Repository: "https://github.com/KiriKirby/phytozome-go",
			Version:    "dev",
			GoVersion:  runtime.Version(),
		},
		UserSession: session,
		System: SystemInfo{
			OS:           runtime.GOOS,
			OSVersion:    "not available in this sample run; no OS-specific probe was performed for report generation",
			Architecture: runtime.GOARCH,
			CPUCount:     runtime.NumCPU(),
			Memory:       "not available in this sample run; memory details are not captured by the sample workflow",
		},
		TimeWindow: TimeWindow{
			QueryStart:     queryStart,
			SearchEnd:      searchEnd,
			ReviewStart:    reviewStart,
			ExportStart:    exportStart,
			ExportEnd:      exportEnd,
			ReportRendered: now,
		},
		Files: files,
		Blast: BlastReportData{
			Database: "lemna.org",
			Species: SpeciesReport{
				DisplayLabel: "Spirodela polyrhiza 7498 v3",
				GenomeLabel:  "Sp7498v3",
				CommonName:   "greater duckweed",
				SearchAlias:  "Spirodela polyrhiza",
				JBrowseName:  "Sp7498v3",
				ProteomeID:   "not available in this sample run",
				ReleaseDate:  "2024-11-18",
				IsOfficial:   "true",
				SourceNotes:  "sample BLAST target context; local BLAST+ fallback used already-downloaded protein FASTA and generated result rows before report rendering",
			},
			Execution: BlastExecutionReport{
				Program:          "BLASTP",
				ExecutionMode:    "local BLAST+ fallback",
				QueryKind:        "protein",
				TargetType:       "proteome",
				EValue:           "1e-5",
				ComparisonMatrix: "BLOSUM62",
				WordLength:       "default",
				AlignmentsToShow: 100,
				AllowGaps:        "true",
				FilterQuery:      "true",
				ServerCapability: "online protein BLAST was unavailable for the selected lemna target in this sample state",
				LocalCapability:  "protein FASTA and makeblastdb-compatible local database were already available during execution",
				Fallback:         "user chose local BLAST+ after capability detection",
				Notes:            "No BLAST, FASTA, or BLAST+ capability check was performed for this report; these values are sample workflow state.",
			},
			Inputs: []BlastInputTrace{
				{Order: 1, RawPreview: ">A.thaliana PAL1|AT2G37040.1 (PAL1)", InputType: "FASTA record", ParserPath: "FASTA header -> sequence sanitize -> label from parenthetical", Source: "pasted FASTA", SequenceLength: 711, LabelName: "PAL1", GeneID: "AT2G37040", TranscriptID: "AT2G37040.1", ProteinID: "AT2G37040.1", Outcome: "resolved", Notes: "Used directly as protein query sequence."},
				{Order: 2, RawPreview: "https://phytozome-next.jgi.doe.gov/report/protein/Athaliana/AT3G53260.1", InputType: "report URL", ParserPath: "URL normalize -> report protein resolver -> query source", Source: "Phytozome report URL", SequenceLength: 706, LabelName: "PAL2", GeneID: "AT3G53260", TranscriptID: "AT3G53260.1", ProteinID: "AT3G53260.1", OriginalURL: "https://phytozome-next.jgi.doe.gov/report/protein/Athaliana/AT3G53260.1?x=1", NormalizedURL: "https://phytozome-next.jgi.doe.gov/report/protein/Athaliana/AT3G53260.1", Outcome: "resolved", Notes: "Query source differs from selected lemna target source."},
				{Order: 3, RawPreview: "MASTTTTTTQQQQLLLL... inline protein token", InputType: "plain sequence", ParserPath: "inline token -> sequence sanitize", Source: "direct sequence", SequenceLength: 521, LabelName: "PAL-like", Outcome: "resolved", Notes: "No source gene identifier was available; label came from manual batch label input."},
				{Order: 4, RawPreview: "load \"pal_family.txt\"", InputType: "loaded file", ParserPath: "load command -> application directory .txt -> normal parser", Source: "sample loaded file", SequenceLength: 0, Outcome: "expanded", Notes: "Loaded file content produced the three records above before BLAST execution."},
			},
			Runs: []BlastRunReport{
				{RunIndex: 1, Label: "PAL1", FamilyName: "PAL", Program: "BLASTP", ExecutionMode: "local", JobID: "local:pal1:makeblastdb-sample", RowCount: 18, SelectedRows: 7, TopHit: "Sp7498v3_PAL_A", BestEValue: "2.1e-118", BestIdentity: "82.4%", Message: "local BLAST result loaded", ResultHash: "sample-result-hash-pal1"},
				{RunIndex: 2, Label: "PAL2", FamilyName: "PAL", Program: "BLASTP", ExecutionMode: "local", JobID: "local:pal2:makeblastdb-sample", RowCount: 16, SelectedRows: 6, TopHit: "Sp7498v3_PAL_B", BestEValue: "4.8e-111", BestIdentity: "79.2%", Message: "local BLAST result loaded", ResultHash: "sample-result-hash-pal2"},
				{RunIndex: 3, Label: "PAL-like", FamilyName: "PAL", Program: "BLASTP", ExecutionMode: "local", JobID: "local:pallike:makeblastdb-sample", RowCount: 12, SelectedRows: 4, TopHit: "Sp7498v3_PAL_C", BestEValue: "7.4e-72", BestIdentity: "61.8%", Message: "local BLAST result loaded", ResultHash: "sample-result-hash-pallike"},
				{RunIndex: 4, Label: "PAL family export", FamilyName: "PAL", Program: "BLASTP", ExecutionMode: "local", JobID: "family:PAL", RowCount: 27, SelectedRows: 12, TopHit: "Sp7498v3_PAL_A", BestEValue: "2.1e-118", BestIdentity: "82.4%", Message: "Family BLAST group PAL merged 3 query runs.", ResultHash: "sample-family-result-hash"},
			},
			Selection: BlastSelectionStats{
				ParsedQueries:     4,
				ResolvedQueries:   3,
				ExecutedRuns:      3,
				ExportedRuns:      1,
				ZeroHitRuns:       0,
				TotalRows:         27,
				SelectedRows:      12,
				UnselectedRows:    15,
				RowsWithURL:       22,
				RowsWithSequence:  25,
				RowsWithTargetLen: 27,
				RowsWithCoverage:  27,
				RowsWithEValue:    27,
				RowsWithIdentity:  27,
				GeneratedFiles:    len(files),
			},
			ExternalReferences: ExternalReferenceReport{
				UniProtEnabled:  true,
				InterProEnabled: true,
				UniProt: UniProtReferenceReport{
					LookupSummary: []NameValue{
						{Name: "Endpoint", Value: "rest.uniprot.org/uniprotkb/search", Explanation: "TSV search endpoint used during the real enrichment step."},
						{Name: "Grouped lookups", Value: "19 unique target keys", Explanation: "Rows with the same lookup key were checked once and then applied to grouped rows."},
						{Name: "Candidate terms", Value: "accession, protein, subject_id, sequence_id, transcript_id, defline", Explanation: "The normal workflow tried already-known identifiers and extracted accessions."},
					},
					Outcome: []NameValue{
						{Name: "Rows with accession", Value: "18 of 27", Explanation: "Rows received a UniProt accession during enrichment."},
						{Name: "Reviewed entries", Value: "5 of 18", Explanation: "Reviewed Swiss-Prot entries among matched rows."},
						{Name: "Canonical length ratio", Value: "16 of 27", Explanation: "Rows with enough target and UniProt length data for length-ratio review."},
					},
					Rows: []UniProtRowSummary{
						{Row: 1, Label: "PAL1", Target: "Sp7498v3_PAL_A", Accession: "Q9PAL1", Reviewed: "reviewed", LengthRatio: "102.27%", Fragment: "false", Caution: "", Annotation: "phenylalanine ammonia-lyase; EC 4.3.1.24"},
						{Row: 5, Label: "PAL2", Target: "Sp7498v3_PAL_B", Accession: "A0A7PAL2", Reviewed: "unreviewed", LengthRatio: "96.83%", Fragment: "false", Caution: "", Annotation: "phenylalanine ammonia-lyase family protein"},
						{Row: 14, Label: "PAL-like", Target: "Sp7498v3_PAL_frag", Accession: "A0A7FRAG", Reviewed: "unreviewed", LengthRatio: "48.10%", Fragment: "true", Caution: "sequence conflict", Annotation: "partial aromatic amino-acid lyase-like protein"},
					},
				},
				InterPro: InterProReferenceReport{
					Settings: []NameValue{
						{Name: "Match Pfam IDs", Value: "true", Explanation: "Shared Pfam IDs contribute to the InterPro status label."},
						{Name: "Match InterPro IDs", Value: "true", Explanation: "Shared InterPro IDs contribute to the InterPro status label."},
						{Name: "Match member-database signature IDs", Value: "true", Explanation: "Shared member signatures contribute supporting evidence."},
						{Name: "Require compatible entry type", Value: "true", Explanation: "Domain/family/homologous_superfamily/repeat/site entries are treated as conserved candidates."},
						{Name: "Also compare entry names", Value: "false", Explanation: "Entry-name string equality was not required in this run."},
						{Name: "Use coverage cutoffs", Value: "true", Explanation: "Coverage thresholds control present versus partial status."},
						{Name: "Use coordinate overlap evidence", Value: "true", Explanation: "Region-level evidence contributes to match scoring."},
						{Name: "present coverage >= %", Value: "70", Explanation: "Matched coverage at or above 70% can support present status."},
						{Name: "partial coverage >= %", Value: "25", Explanation: "Matched coverage at or above 25% can support partial status."},
						{Name: "present evidence count >=", Value: "1", Explanation: "At least one matched conserved item is required for present status."},
						{Name: "partial evidence count >=", Value: "1", Explanation: "At least one matched conserved item is required for partial status."},
					},
					Outcome: []NameValue{
						{Name: "Query entry", Value: "available", Explanation: "The query-side PAL1 UniProt accession had InterPro matches during enrichment."},
						{Name: "Rows with InterPro entry", Value: "20 of 27", Explanation: "Rows with at least one InterPro API entry from already-run enrichment."},
						{Name: "Rows with conserved region present/partial", Value: "15 of 27", Explanation: "Rows with present or partial conserved-region evidence under sample settings."},
					},
					StatusCounts: []NameValue{
						{Name: "present", Value: "11", Explanation: "Matched items and coverage met present thresholds."},
						{Name: "partial", Value: "4", Explanation: "Conserved evidence existed but did not meet present thresholds."},
						{Name: "missing", Value: "6", Explanation: "No conserved match was found against query evidence."},
						{Name: "uncertain", Value: "2", Explanation: "Evidence existed but remained below configured status thresholds."},
						{Name: "blank", Value: "4", Explanation: "No InterPro hit entry was available in sample rows."},
					},
				},
			},
			Family: &FamilyBlastReport{
				Settings: []NameValue{
					{Name: "Group related queries as one family result", Value: "true", Explanation: "Family BLAST grouped detected PAL member queries after individual BLAST execution."},
					{Name: "Used custom group editor", Value: "true", Explanation: "The Family BLAST group editor was opened so final groups could be reviewed or changed."},
					{Name: "Detect families from query names automatically", Value: "true", Explanation: "Common label prefixes were used to derive family groups."},
					{Name: "Merge rows that hit the same target gene/protein", Value: "true", Explanation: "Rows from member queries were merged by normalized target key."},
					{Name: "When merged, keep the strongest member hit", Value: "true", Explanation: "One best-ranked row was kept when several member queries hit the same target."},
					{Name: "minimum queries in a family", Value: "2", Explanation: "At least two member queries were required for a family group."},
					{Name: "Remove Arabidopsis At/AT prefix for grouping", Value: "false", Explanation: "Leading At/AT was preserved for family-name derivation in this sample."},
					{Name: "Remove trailing member number", Value: "true", Explanation: "Trailing numeric member indexes were removed."},
					{Name: "Ignore suffix after a member number", Value: "true", Explanation: "Suffixes after member numbers were normalized before final family name creation."},
					{Name: "Use UniProt evidence when ranking merged rows", Value: "true", Explanation: "UniProt evidence contributed to best-hit merge ranking."},
					{Name: "Use InterPro evidence when ranking merged rows", Value: "true", Explanation: "InterPro conserved-region evidence contributed to best-hit merge ranking."},
				},
				Groups: []FamilyBlastGroupReport{
					{Name: "PAL", MemberLabels: []string{"PAL1", "PAL2", "PAL-like"}, GroupSource: "customized groups", DetectionRule: "customized in Family BLAST group editor", OriginalRuns: 3, RowsBefore: 46, RowsAfter: 27, OutputBaseName: "PAL"},
				},
				MergeRecords: []FamilyMergeRecord{
					{Family: "PAL", TargetKey: "sp7498v3_pal_a", MemberRows: "PAL1 row 1; PAL2 row 3", ChosenRow: "PAL1 row 1", Reason: "higher reference score, lower E-value", ScoreDetails: "InterPro present +80; UniProt reviewed +30; length near +25"},
					{Family: "PAL", TargetKey: "sp7498v3_pal_frag", MemberRows: "PAL-like row 14; PAL2 row 12", ChosenRow: "PAL2 row 12", Reason: "fragment penalty removed the lower-ranked row", ScoreDetails: "fragment -30; missing InterPro -80 on rejected row"},
				},
			},
			Filter: &BlastFilterReport{
				Applied:              true,
				Cleared:              false,
				RecommendedKeep:      15,
				RecommendedRemove:    12,
				FinalSelected:        12,
				FinalUnselected:      15,
				UserRescued:          2,
				UserRemovedAfterKeep: 5,
				Settings:             sampleBlastFilterSettings(),
				Formulas:             BlastFilterFormulas(sampleBlastFilterTotals(), model.DefaultBlastFilterSettings()),
				Totals:               sampleBlastFilterTotals(),
				QuerySummaries: []BlastFilterQuerySummary{
					{Query: "PAL1", Family: "PAL", TotalRows: 10, RecommendedKeep: 6, RecommendedRemove: 4, FinalSelected: 5, FinalUnselected: 5, UserRescued: 1, UserRemoved: 2, MatchedRows: 7, Difference: -1, AgreementPercent: "70.0%"},
					{Query: "PAL2", Family: "PAL", TotalRows: 9, RecommendedKeep: 5, RecommendedRemove: 4, FinalSelected: 4, FinalUnselected: 5, UserRescued: 1, UserRemoved: 2, MatchedRows: 6, Difference: -1, AgreementPercent: "66.7%"},
					{Query: "PAL-like", Family: "PAL", TotalRows: 8, RecommendedKeep: 4, RecommendedRemove: 4, FinalSelected: 3, FinalUnselected: 5, UserRescued: 0, UserRemoved: 1, MatchedRows: 7, Difference: -1, AgreementPercent: "87.5%"},
				},
				HardRuleSummaries: []BlastFilterRuleSummary{
					{Name: "Identity threshold", Result: "not active", Passed: 27, Failed: 0, Rule: "MinIdentityPercent=0", Explanation: "Identity was not used as a hard removal rule in this run.", Source: "BLAST percent_identity"},
					{Name: "Query coverage threshold", Result: "not active", Passed: 27, Failed: 0, Rule: "MinAlignQueryCoveragePercent=0", Explanation: "Coverage was not used as a hard removal rule in this run.", Source: "BLAST coverage"},
					{Name: "E-value threshold", Result: "not active", Passed: 27, Failed: 0, Rule: "MaxEValue=0", Explanation: "E-value was not used as a hard removal rule in this run.", Source: "BLAST e_value"},
					{Name: "Canonical length ratio", Result: "warning", Passed: 22, Failed: 5, Rule: "70 <= ratio <= 130 and ratio required", Explanation: "Rows outside the accepted ratio or missing required ratio were suggested for removal.", Source: "UniProt length comparison"},
					{Name: "UniProt accession required", Result: "not active", Passed: 27, Failed: 0, Rule: "RequireUniProtAccession=false", Explanation: "Rows were not removed solely for missing UniProt accessions.", Source: "UniProt accession"},
					{Name: "UniProt fragment rejection", Result: "warning", Passed: 24, Failed: 3, Rule: "RejectUniProtFragments=true", Explanation: "Fragment-marked UniProt rows were suggested for removal.", Source: "UniProt fragment"},
					{Name: "UniProt sequence caution rejection", Result: "not active", Passed: 27, Failed: 0, Rule: "RejectUniProtSequenceCautions=false", Explanation: "Sequence-caution rows were not automatically removed by this setting.", Source: "UniProt sequence caution"},
					{Name: "InterPro conserved-region requirement", Result: "warning", Passed: 19, Failed: 8, Rule: "present or allowed partial; reject missing/uncertain", Explanation: "Rows with missing, uncertain, or blank conserved-region status were suggested for removal.", Source: "InterPro status"},
					{Name: "InterPro coverage threshold", Result: "not active", Passed: 27, Failed: 0, Rule: "MinInterProCoveragePercent=0 and coverage not required", Explanation: "InterPro coverage did not act as a hard removal threshold.", Source: "InterPro coverage"},
				},
			},
			Provenance: []ProvenanceSlice{
				{Label: "user query input", Count: 19, Explanation: "FASTA headers, direct sequence labels, and report URLs supplied in the BLAST input step."},
				{Label: "query resolver metadata", Count: 22, Explanation: "Normalized URL and query source identifiers resolved before BLAST submission."},
				{Label: "BLAST execution result", Count: 244, Explanation: "Alignment metrics and hit identifiers returned by local BLAST result parsing."},
				{Label: "target source metadata", Count: 81, Explanation: "Target-side identifiers and report URLs attached to BLAST rows."},
				{Label: "UniProt enrichment", Count: 126, Explanation: "Optional UniProt values added during normal enrichment."},
				{Label: "InterPro enrichment", Count: 95, Explanation: "Optional InterPro values and conserved-region statuses added during enrichment."},
				{Label: "family/filter/export generated", Count: 73, Explanation: "Family group labels, filter flags, row numbers, file metadata, and report-generated audit values."},
				{Label: "unavailable/missing", Count: 34, Explanation: "Fields absent from current rows or not captured in this sample workflow state."},
			},
			ColumnCompleteness: sampleBlastColumnCompleteness(),
			QualityChecks:      sampleBlastQualityChecks(),
			Columns:            sampleBlastColumns("lemna", "BLASTP", true, true),
			ExportSettings: []NameValue{
				{Name: "Export mode", Value: "Family BLAST single group", Explanation: "One family group was exported from three executed query runs."},
				{Name: "File base name", Value: "PAL", Explanation: "Family name used for selected Excel, raw Excel, TXT, raw TXT, and report context."},
				{Name: "Output folder", Value: session.OutputDir, Explanation: "Destination folder for this sample BLAST export action."},
				{Name: "Write selected Excel", Value: "true", Explanation: "Selected rows are written to the main workbook."},
				{Name: "Write raw Excel and raw text", Value: "true", Explanation: "All current family rows are written to _raw.xlsx, and all current peptide records are written to _raw.txt."},
				{Name: "Write peptide text", Value: "true", Explanation: "Selected hit peptides and prepended query sequences are written to TXT."},
				{Name: "Write report PDF", Value: "true", Explanation: "One PDF report is written for this export action."},
				{Name: "rowNumbers", Value: "available", Explanation: "Selected Excel row numbers preserve original review table row identities."},
				{Name: "filterFlags", Value: "available", Explanation: "Excel row coloring mirrors final filter suggestion flags where supported."},
			},
			GenerationSteps: sampleBlastSteps(exportStart, now),
			Sequences: SequenceAudit{
				Requested:       true,
				RequestedCount:  15,
				WrittenCount:    14,
				SkippedCount:    1,
				TotalCharacters: 9478,
				TextFileType:    "BLAST peptide TXT with prepended query sequences and selected hit peptide records",
				HeaderLabelMode: "family member query headers use the best available query label; hit records append selected row label_name",
				Records: []SequenceRecord{
					{Row: 0, SearchTerm: "query:PAL1", Label: "PAL1", SequenceID: "AT2G37040.1", Transcript: "AT2G37040.1", Status: "written", Length: 711, Source: "prepended query sequence record"},
					{Row: 0, SearchTerm: "query:PAL2", Label: "PAL2", SequenceID: "AT3G53260.1", Transcript: "AT3G53260.1", Status: "written", Length: 706, Source: "prepended query sequence record"},
					{Row: 0, SearchTerm: "query:PAL-like", Label: "PAL-like", SequenceID: "not available in this run", Transcript: "not available in this run", Status: "written", Length: 521, Source: "prepended direct sequence query record"},
					{Row: 1, SearchTerm: "PAL family export", Label: "PAL", SequenceID: "Sp7498v3_PAL_A", Transcript: "Sp7498v3_T001182", Status: "written", Length: 718, Source: "selected BLAST hit peptide export"},
					{Row: 5, SearchTerm: "PAL family export", Label: "PAL", SequenceID: "Sp7498v3_PAL_B", Transcript: "Sp7498v3_T008441", Status: "written", Length: 702, Source: "selected BLAST hit peptide export"},
					{Row: 19, SearchTerm: "PAL family export", Label: "PAL", SequenceID: "Sp7498v3_PAL_remote", Transcript: "Sp7498v3_T029551", Status: "skipped", Length: 0, Source: "sequence unavailable in current export state"},
				},
				QuerySummaries: []SequenceQuerySummary{
					{QueryLabel: "PAL1", QueryKind: "query sequence record", RequestedCount: 1, WrittenCount: 1, SkippedCount: 0, AverageLength: 711, MinLength: 711, MaxLength: 711, TotalLength: 711, SourceSummary: "prepended query sequence record"},
					{QueryLabel: "PAL2", QueryKind: "query sequence record", RequestedCount: 1, WrittenCount: 1, SkippedCount: 0, AverageLength: 706, MinLength: 706, MaxLength: 706, TotalLength: 706, SourceSummary: "prepended query sequence record"},
					{QueryLabel: "PAL-like", QueryKind: "query sequence record", RequestedCount: 1, WrittenCount: 1, SkippedCount: 0, AverageLength: 521, MinLength: 521, MaxLength: 521, TotalLength: 521, SourceSummary: "prepended direct sequence query record"},
					{QueryLabel: "PAL family export", QueryKind: "selected hit peptide records", RequestedCount: 12, WrittenCount: 11, SkippedCount: 1, AverageLength: 684, MinLength: 661, MaxLength: 718, TotalLength: 7528, SourceSummary: "selected BLAST hit peptide export"},
				},
			},
		},
	}
}

func SampleBlastPhytozomeReportData() ReportData {
	data := SampleBlastReportData()
	data.Blast.Database = "phytozome"
	data.Blast.Species = SpeciesReport{
		DisplayLabel: "Arabidopsis thaliana v12.1",
		GenomeLabel:  "Athaliana_v12.1",
		CommonName:   "thale cress",
		SearchAlias:  "Arabidopsis thaliana",
		JBrowseName:  "Athaliana",
		ProteomeID:   "447",
		ReleaseDate:  "2025-03-14",
		IsOfficial:   "not applicable to this source",
		SourceNotes:  "sample phytozome BLAST context; target rows represent source-side BLAST result parsing rather than lemna release-backed local assets",
	}
	for i := range data.Blast.Runs {
		data.Blast.Runs[i].Program = "BLASTP"
	}
	return data
}

func SampleBlastWithoutReferencesReportData() ReportData {
	data := SampleBlastPhytozomeReportData()
	data.Blast.ExternalReferences = ExternalReferenceReport{}
	for i := range data.Blast.Provenance {
		switch data.Blast.Provenance[i].Label {
		case "UniProt enrichment", "InterPro enrichment":
			data.Blast.Provenance[i].Count = 0
			data.Blast.Provenance[i].Explanation = ""
		}
	}
	data.Blast.Provenance = filterProvenanceLabels(data.Blast.Provenance, []string{"UniProt enrichment", "InterPro enrichment"})
	data.Blast.QualityChecks = filterQualityChecksBySource(data.Blast.QualityChecks, []string{"UniProt enrichment", "InterPro enrichment"})
	if data.Blast.Family != nil {
		for i := range data.Blast.Family.Settings {
			switch data.Blast.Family.Settings[i].Name {
			case "Use UniProt evidence when ranking merged rows", "Use InterPro evidence when ranking merged rows":
				data.Blast.Family.Settings[i].Value = "false"
				data.Blast.Family.Settings[i].Explanation = "External reference scoring was disabled in this sample no-reference BLAST scenario."
			}
		}
		for i := range data.Blast.Family.MergeRecords {
			data.Blast.Family.MergeRecords[i].Reason = "better BLAST-side ranking without external reference scoring"
			data.Blast.Family.MergeRecords[i].ScoreDetails = "BLAST-side ranking only; no UniProt or InterPro score contribution"
		}
	}
	if data.Blast.Filter != nil {
		data.Blast.Filter.Settings = sampleBlastFilterSettingsWithoutReferences()
		data.Blast.Filter.HardRuleSummaries = sampleBlastFilterHardRulesWithoutReferences()
		data.Blast.Filter.Formulas = sampleBlastFilterFormulasWithoutReferences(data.Blast.Filter.Totals)
	}
	data.Blast.Columns = sampleBlastColumns("phytozome", "BLASTP", false, false)
	data.Blast.ColumnCompleteness = filterCompletenessWithoutLabels(data.Blast.ColumnCompleteness, []string{"UniProt accession", "InterPro conserved region status"})
	return data
}

func filterCompletenessWithoutLabels(columns []ColumnCompleteness, labels []string) []ColumnCompleteness {
	omit := map[string]struct{}{}
	for _, label := range labels {
		omit[label] = struct{}{}
	}
	out := make([]ColumnCompleteness, 0, len(columns))
	for _, col := range columns {
		if _, ok := omit[col.Column]; ok {
			continue
		}
		out = append(out, col)
	}
	return out
}

func filterProvenanceLabels(values []ProvenanceSlice, labels []string) []ProvenanceSlice {
	omit := map[string]struct{}{}
	for _, label := range labels {
		omit[label] = struct{}{}
	}
	out := make([]ProvenanceSlice, 0, len(values))
	for _, value := range values {
		if _, ok := omit[value.Label]; ok {
			continue
		}
		out = append(out, value)
	}
	return out
}

func filterQualityChecksBySource(values []QualityCheck, sources []string) []QualityCheck {
	omit := map[string]struct{}{}
	for _, source := range sources {
		omit[source] = struct{}{}
	}
	out := make([]QualityCheck, 0, len(values))
	for _, value := range values {
		if _, ok := omit[value.Source]; ok {
			continue
		}
		out = append(out, value)
	}
	return out
}

func sampleSession() UserSessionInfo {
	wd, _ := os.Getwd()
	exe, _ := os.Executable()
	usr, _ := user.Current()
	host, _ := os.Hostname()
	userName := os.Getenv("USERNAME")
	if userName == "" {
		userName = os.Getenv("USER")
	}
	if userName == "" && usr != nil {
		userName = usr.Username
	}
	home := ""
	if usr != nil {
		home = usr.HomeDir
	}
	outputDir := filepath.Join(wd, "output")
	cacheDir := filepath.Join(wd, ".cache")
	return UserSessionInfo{
		UserName:       valueOr(userName, "not available in this run"),
		HomeDir:        valueOr(home, "not available in this run"),
		SessionName:    firstEnv("WT_SESSION", "TERM_SESSION_ID", "SESSIONNAME"),
		HostName:       valueOr(host, "not available in this run"),
		ProcessID:      os.Getpid(),
		ExecutablePath: valueOr(exe, "not available in this run"),
		WorkingDir:     valueOr(wd, "not available in this run"),
		AppDir:         valueOr(filepath.Dir(exe), "not available in this run"),
		OutputDir:      outputDir,
		CacheDir:       cacheDir,
		Terminal:       firstEnv("TERM_PROGRAM", "WT_SESSION", "TERM", "ComSpec"),
		TerminalDetail: strings.Join(nonEmpty([]string{
			envPair("TERM_PROGRAM_VERSION"),
			envPair("WT_SESSION"),
			envPair("TERM"),
			envPair("SESSIONNAME"),
		}), "; "),
	}
}

func sampleFiles(now time.Time, outputDir string) []GeneratedFile {
	return []GeneratedFile{
		sampleFile(now, outputDir, "spirodela_lignin_keyword.xlsx", "selected Excel", "selected keyword rows exported as the main review workbook", 28541),
		sampleFile(now, outputDir, "spirodela_lignin_keyword_raw.xlsx", "raw Excel", "all current keyword rows exported for audit comparison", 49322),
		sampleFile(now, outputDir, "spirodela_lignin_keyword_raw.txt", "raw peptide text", "all current keyword peptide records exported for audit comparison", 18452),
		sampleFile(now, outputDir, "spirodela_lignin_keyword.txt", "peptide text", "peptide FASTA-style sequence records for selected rows", 7148),
	}
}

func sampleBlastFiles(now time.Time, outputDir string) []GeneratedFile {
	return []GeneratedFile{
		sampleFile(now, outputDir, "PAL.xlsx", "selected BLAST Excel", "selected Family BLAST rows exported after filter-assisted review", 38428),
		sampleFile(now, outputDir, "PAL_raw.xlsx", "raw BLAST Excel", "all current Family BLAST rows exported for audit comparison", 81240),
		sampleFile(now, outputDir, "PAL_raw.txt", "raw BLAST peptide text", "all current Family BLAST peptide records exported for audit comparison", 39812),
		sampleFile(now, outputDir, "PAL.txt", "BLAST peptide text", "prepended PAL query sequences plus selected target peptide records", 18244),
	}
}

func sampleBlastFilterSettings() []BlastFilterSettingDetail {
	return BlastFilterSettingDetails(model.DefaultBlastFilterSettings())
}

func sampleBlastFilterSettingsWithoutReferences() []BlastFilterSettingDetail {
	settings := model.DefaultBlastFilterSettings()
	settings.UseTargetCanonicalLengthRatio = false
	settings.RequireTargetCanonicalLengthRatio = false
	settings.RequireUniProtAccession = false
	settings.PreferUniProtReviewed = false
	settings.RejectUniProtFragments = false
	settings.RejectUniProtSequenceCautions = false
	settings.RequireInterProConservedRegion = false
	settings.AllowInterProPartial = false
	settings.RejectInterProMissing = false
	settings.RejectInterProUncertain = false
	settings.MinInterProCoveragePercent = 0
	settings.RequireInterProCoverageWhenUsed = false
	return BlastFilterSettingDetails(settings)
}

func sampleBlastFilterTotals() BlastFilterTotals {
	return BlastFilterTotals{
		QueryCount:        3,
		TotalRows:         27,
		RecommendedKeep:   15,
		RecommendedRemove: 12,
		FinalSelected:     12,
		FinalUnselected:   15,
		UserRescued:       2,
		UserRemoved:       5,
		MatchedRows:       20,
		AgreementPercent:  "74.1%",
		DifferenceRows:    7,
	}
}

func sampleBlastColumnCompleteness() []ColumnCompleteness {
	return []ColumnCompleteness{
		{Column: "row", FilledRows: 12, EmptyRows: 0, TotalRows: 12, FilledRatio: "100.0%", Source: "phytozome GO export"},
		{Column: "source_database", FilledRows: 12, EmptyRows: 0, TotalRows: 12, FilledRatio: "100.0%", Source: "workflow annotation"},
		{Column: "blast_program", FilledRows: 12, EmptyRows: 0, TotalRows: 12, FilledRatio: "100.0%", Source: "BLAST request"},
		{Column: "label_name", FilledRows: 12, EmptyRows: 0, TotalRows: 12, FilledRatio: "100.0%", Source: "BLAST label/family workflow"},
		{Column: "protein", FilledRows: 12, EmptyRows: 0, TotalRows: 12, FilledRatio: "100.0%", Source: "BLAST result"},
		{Column: "e_value", FilledRows: 12, EmptyRows: 0, TotalRows: 12, FilledRatio: "100.0%", Source: "BLAST result"},
		{Column: "percent_identity", FilledRows: 12, EmptyRows: 0, TotalRows: 12, FilledRatio: "100.0%", Source: "BLAST result"},
		{Column: "align_query_length_percent", FilledRows: 12, EmptyRows: 0, TotalRows: 12, FilledRatio: "100.0%", Source: "BLAST result / computed from query length"},
		{Column: "gene_report_url", FilledRows: 10, EmptyRows: 2, TotalRows: 12, FilledRatio: "83.3%", Source: "target source metadata"},
		{Column: "UniProt accession", FilledRows: 9, EmptyRows: 3, TotalRows: 12, FilledRatio: "75.0%", Source: "UniProt enrichment"},
		{Column: "InterPro conserved region status", FilledRows: 10, EmptyRows: 2, TotalRows: 12, FilledRatio: "83.3%", Source: "InterPro enrichment"},
	}
}

func sampleBlastQualityChecks() []QualityCheck {
	return []QualityCheck{
		{Name: "Unresolved or skipped query records", Result: "pass", Count: "0 unresolved / 3 executable", Rule: "warn when parsed records fail resolution", Explanation: "All executable sample records became query sequences; the load command itself expanded to content.", Source: "input trace"},
		{Name: "Query sequence length available", Result: "pass", Count: "3 of 3", Rule: "warn when exported run lacks query length", Explanation: "All member query sequences have known lengths.", Source: "query resolution"},
		{Name: "BLAST job/result identifier available", Result: "pass", Count: "3 local job markers", Rule: "warn when no job or local marker is available", Explanation: "Each member query has a local result marker in sample state.", Source: "BLAST result"},
		{Name: "Alignment metrics present", Result: "pass", Count: "12 of 12 selected rows", Rule: "warn when E-value, identity, or coverage is missing", Explanation: "Selected rows contain core BLAST metrics.", Source: "selected rows"},
		{Name: "Stable target identifier available", Result: "pass", Count: "12 of 12 selected rows", Rule: "warn when no target identifier exists", Explanation: "Selected rows have protein or sequence IDs.", Source: "selected rows"},
		{Name: "UniProt coverage", Result: "warning", Count: "9 of 12 selected rows", Rule: "warn when UniProt requested but missing for selected rows", Explanation: "Three selected rows lack UniProt accession; this limits reference evidence.", Source: "UniProt enrichment"},
		{Name: "InterPro status availability", Result: "warning", Count: "10 of 12 selected rows", Rule: "warn when InterPro requested but status is blank", Explanation: "Two selected rows lack InterPro conserved-region status.", Source: "InterPro enrichment"},
		{Name: "Family merge audit available", Result: "pass", Count: "2 merge records", Rule: "warn when merged best-ranked rows are not recorded", Explanation: "Sample family merge records show chosen row and reason.", Source: "Family BLAST state"},
		{Name: "Filter/final selection difference visible", Result: "pass", Count: "2 rescued / 5 user removed", Rule: "warn when filter flags or final selection is missing", Explanation: "Sample report can compare filter suggestions with final user selection.", Source: "filter flags + selection"},
		{Name: "Peptide text sequence completeness", Result: "warning", Count: "14 written / 15 requested", Rule: "warn when written < requested", Explanation: "One selected target sequence was unavailable in sample export state.", Source: "sequence audit"},
	}
}

func sampleBlastFilterHardRulesWithoutReferences() []BlastFilterRuleSummary {
	return []BlastFilterRuleSummary{
		{Name: "Identity threshold", Result: "not active", Passed: 27, Failed: 0, Rule: "MinIdentityPercent=0", Explanation: "Identity was not used as a hard removal rule in this sample no-reference run.", Source: "BLAST percent_identity"},
		{Name: "Query coverage threshold", Result: "not active", Passed: 27, Failed: 0, Rule: "MinAlignQueryCoveragePercent=0", Explanation: "Coverage was not used as a hard removal rule in this sample no-reference run.", Source: "BLAST coverage"},
		{Name: "E-value threshold", Result: "not active", Passed: 27, Failed: 0, Rule: "MaxEValue=0", Explanation: "E-value was not used as a hard removal rule in this sample no-reference run.", Source: "BLAST e_value"},
	}
}

func sampleBlastFilterFormulasWithoutReferences(totals BlastFilterTotals) []NameValue {
	agreement := totals.AgreementPercent
	if agreement == "" {
		agreement = "not available"
	}
	return []NameValue{
		{Name: "query_coverage_percent", Value: "AlignQueryLengthPercent if present, otherwise AlignLength / QueryLength * 100", Explanation: "The report uses the captured BLAST coverage field first and only reconstructs it from alignment length and query length when the cached field is missing."},
		{Name: "remove_by_hard_rules", Value: "RejectIfAnyHardRuleFails AND any active BLAST-side hard rule fails", Explanation: "Only BLAST-side hard rules participate in this no-reference sample because external-reference gates were disabled."},
		{Name: "remove_by_soft_score", Value: "EnableSoftScore AND score < MinSoftScore", Explanation: "Soft scoring can remove rows only when it is enabled in the settings."},
		{Name: "final_filter_recommendation", Value: "remove_by_hard_rules OR remove_by_soft_score OR removed_by_best_isoform_limit OR removed_by_top_hit_limit", Explanation: "The final recommendation combines BLAST-side hard rules, optional soft scoring, and selection-limiting rules."},
		{Name: "agreement_rate", Value: fmt.Sprintf("%d / %d = %s", totals.MatchedRows, totals.TotalRows, agreement), Explanation: "This is the share of rows where the automatic recommendation and the final user selection agree."},
		{Name: "difference_rows", Value: fmt.Sprintf("%d", totals.DifferenceRows), Explanation: "Rows that differ between the automatic recommendation and final selection are rescued or manually removed rows."},
	}
}

func sampleBlastColumns(database string, program string, includeUniProt bool, includeInterPro bool) []ColumnLineage {
	ids := prompt.BlastReportColumnIDs(database, program, includeUniProt, includeInterPro)
	out := make([]ColumnLineage, 0, len(ids))
	for _, id := range ids {
		help := prompt.ColumnHelpEnglish(id)
		out = append(out, ColumnLineage{
			ID:               id,
			Column:           prompt.ColumnExportHeader(id, prompt.ColumnDisplayOptions{DatabaseDisplay: database}),
			Meaning:          valueOr(help, id),
			EnglishDetail:    help,
			ChineseDetail:    prompt.ColumnHelpChinese(id),
			JapaneseDetail:   prompt.ColumnHelpJapanese(id),
			Source:           sampleColumnSource(id, database),
			CollectionMethod: sampleColumnCollection(id, database),
			BlankMeaning:     sampleColumnBlankMeaning(id, database),
			UsedInStats:      sampleColumnStatsUse(id),
		})
	}
	return out
}

func sampleBlastSteps(start time.Time, now time.Time) []GenerationStep {
	cursor := start
	makeStep := func(name string, ms int64, status string, details string) GenerationStep {
		step := GenerationStep{Name: name, Start: cursor, End: cursor.Add(time.Duration(ms) * time.Millisecond), DurationMS: ms, Status: status, Details: details}
		cursor = step.End.Add(280 * time.Millisecond)
		return step
	}
	return []GenerationStep{
		makeStep("Resolve BLAST export directory", 54, "ok", "output folder resolved before file writing"),
		makeStep("Write selected BLAST Excel", 842, "ok", "12 selected Family BLAST rows written with rowNumbers/filterFlags"),
		makeStep("Write raw BLAST Excel", 1395, "ok", "27 current Family BLAST rows written for audit comparison"),
		makeStep("Write raw Family BLAST peptide text", 686, "ok", "all current family hit records written to PAL_raw.txt"),
		makeStep("Fetch/use BLAST peptide sequences", 5380, "warning", "14 sequence records available, 1 selected hit unavailable"),
		makeStep("Prepend query sequence records", 88, "ok", "3 family member query records prepended to TXT output"),
		makeStep("Write BLAST peptide text", 477, "ok", "query records plus selected hit records written"),
		makeStep("Capture file metadata and hashes", 221, "ok", "4 generated data files inspected in sample data"),
		makeStep("Render BLAST report PDF", now.Sub(cursor).Milliseconds(), "ok", "PDF report rendered from structured BLAST sample data"),
	}
}

func sampleFile(now time.Time, dir string, name string, typ string, role string, size int64) GeneratedFile {
	path := filepath.Join(dir, name)
	payload := []byte(fmt.Sprintf("%s|%s|%d|%s", name, typ, size, now.Format(time.RFC3339Nano)))
	sha256Sum := sha256.Sum256(payload)
	sha1Sum := sha1.Sum(payload)
	md5Sum := md5.Sum(payload)
	return GeneratedFile{
		Name:         name,
		Type:         typ,
		Role:         role,
		Path:         path,
		SizeBytes:    size,
		CreatedAt:    now.Add(-90 * time.Second),
		ModifiedAt:   now.Add(-35 * time.Second),
		AccessedAt:   now.Add(-15 * time.Second),
		Permissions:  "sample metadata; real runs use filesystem mode when captured",
		Owner:        valueOr(os.Getenv("USERNAME"), valueOr(os.Getenv("USER"), "not available in this run")),
		SHA256:       hex.EncodeToString(sha256Sum[:]),
		SHA1:         hex.EncodeToString(sha1Sum[:]),
		MD5:          hex.EncodeToString(md5Sum[:]),
		HashCaptured: now.Add(-8 * time.Second),
	}
}

func sampleKeywordColumns(database string, includeProteinID bool, extra []string) []ColumnLineage {
	ids := prompt.KeywordReportColumnIDs(database, includeProteinID, extra)
	out := make([]ColumnLineage, 0, len(ids))
	for _, id := range ids {
		help := prompt.ColumnHelpEnglish(id)
		out = append(out, ColumnLineage{
			ID:               id,
			Column:           prompt.ColumnExportHeader(id, prompt.ColumnDisplayOptions{DatabaseDisplay: database}),
			Meaning:          valueOr(help, id),
			EnglishDetail:    help,
			ChineseDetail:    prompt.ColumnHelpChinese(id),
			JapaneseDetail:   prompt.ColumnHelpJapanese(id),
			Source:           sampleColumnSource(id, database),
			CollectionMethod: sampleColumnCollection(id, database),
			BlankMeaning:     sampleColumnBlankMeaning(id, database),
			UsedInStats:      sampleColumnStatsUse(id),
		})
	}
	return out
}

func sampleColumnSource(id string, database string) string {
	switch {
	case strings.HasPrefix(id, "gff_"):
		return database + " GFF3"
	case strings.HasPrefix(id, "attr_"):
		return database + " GFF3 attributes"
	case strings.HasPrefix(id, "ahrd_"):
		return database + " AHRD"
	case strings.HasPrefix(id, "uniprot_"):
		return "UniProt enrichment"
	case strings.HasPrefix(id, "interpro_"):
		return "InterPro enrichment"
	case id == "target_uniprot_canonical_length_percent":
		return "UniProt enrichment"
	default:
		return "sample export workflow"
	}
}

func sampleColumnCollection(id string, database string) string {
	switch {
	case id == "row":
		return "generated during export"
	case id == "search_term":
		return "preserved from current query input"
	case strings.HasPrefix(id, "gff_"):
		return "parsed from " + database + " release annotation"
	case strings.HasPrefix(id, "attr_"):
		return "parsed from " + database + " feature attributes"
	case strings.HasPrefix(id, "ahrd_"):
		return "loaded from AHRD annotation records"
	case strings.HasPrefix(id, "uniprot_"):
		return "attached during enrichment"
	case strings.HasPrefix(id, "interpro_"):
		return "attached during enrichment"
	case id == "target_uniprot_canonical_length_percent":
		return "computed from target_length and UniProt canonical length"
	default:
		return "captured from the completed workflow"
	}
}

func sampleColumnBlankMeaning(id string, database string) string {
	switch {
	case strings.HasPrefix(id, "gff_"):
		return "not applicable outside " + database + " release rows"
	case strings.HasPrefix(id, "attr_"):
		return "attribute absent from current feature"
	case strings.HasPrefix(id, "ahrd_"):
		return "AHRD did not provide value"
	case strings.HasPrefix(id, "uniprot_"):
		return "UniProt disabled or no match"
	case strings.HasPrefix(id, "interpro_"):
		return "InterPro disabled or no match"
	case id == "target_uniprot_canonical_length_percent":
		return "UniProt canonical length unavailable"
	default:
		return "not available in this run"
	}
}

func sampleColumnStatsUse(id string) string {
	switch {
	case id == "row", id == "search_term", id == "label_name", id == "source_database", id == "blast_program":
		return "traceability"
	case strings.Contains(id, "identity"), strings.Contains(id, "coverage"), strings.Contains(id, "length"):
		return "quality"
	default:
		return "review"
	}
}

func sampleSteps(start time.Time, now time.Time) []GenerationStep {
	cursor := start
	makeStep := func(name string, ms int64, status string, details string) GenerationStep {
		step := GenerationStep{Name: name, Start: cursor, End: cursor.Add(time.Duration(ms) * time.Millisecond), DurationMS: ms, Status: status, Details: details}
		cursor = step.End.Add(350 * time.Millisecond)
		return step
	}
	return []GenerationStep{
		makeStep("Resolve output directory", 42, "ok", "output directory resolved from application path"),
		makeStep("Write selected Excel", 731, "ok", "11 selected rows written"),
		makeStep("Write raw Excel", 1048, "ok", "23 current rows written"),
		makeStep("Write raw peptide text", 502, "ok", "all current keyword peptide records written to _raw.txt"),
		makeStep("Use peptide sequences", 4260, "warning", "10 written, 1 skipped because sequence ID was unavailable"),
		makeStep("Write peptide text", 388, "ok", "10 records written"),
		makeStep("Capture file metadata", 96, "ok", "4 generated files inspected in sample data"),
		makeStep("Compute hashes", 183, "ok", "SHA-256, SHA-1, and MD5 captured"),
		makeStep("Render report PDF", now.Sub(cursor).Milliseconds(), "ok", "PDF report was written from completed sample export data"),
	}
}

func firstEnv(names ...string) string {
	for _, name := range names {
		if value := strings.TrimSpace(os.Getenv(name)); value != "" {
			return fmt.Sprintf("%s=%s", name, value)
		}
	}
	return "not available in this run"
}

func envPair(name string) string {
	value := strings.TrimSpace(os.Getenv(name))
	if value == "" {
		return ""
	}
	return fmt.Sprintf("%s=%s", name, value)
}

func nonEmpty(values []string) []string {
	out := make([]string, 0, len(values))
	for _, value := range values {
		if strings.TrimSpace(value) != "" {
			out = append(out, value)
		}
	}
	if len(out) == 0 {
		return []string{"not available in this run"}
	}
	return out
}
